### ISSUE TITLE
weird errors

### ISSUE THREAD

**Issue by kawka-maxim** [lagcomp/csgo_sdk#111]
so i cloned the base onto my desktop opened it and it compiled just fine but, i wonder why i have errors like these in every single file and if it is possible to disable them [snip](https://imgur.com/laqiYQV)

**Comment by lagcomp** [comment]
clearly a visual-studio problem, iirc they had this problem w clang-cl toolset if /std:c++20 standard is selected, but now this problem is solved
so try to either update visual-studio or change the toolset to msvc or change the c++ language standard to /std:c++latest
