### ISSUE TITLE
weapon_info is always zero.

### ISSUE THREAD

**Issue by pinkway** [lagcomp/csgo_sdk#117]
![XIRUrc2P780](https://user-images.githubusercontent.com/131168457/232782200-43e07f68-0a74-42df-a238-7d802f9ad9d8.jpg)

**Comment by lagcomp** [comment]
weapon_info in the local_player class is set after calling the c_move::handle

**Comment by pinkway** [comment]
"weapon_info in the local_player class is set after calling the c_move::handle", i knew about this so i moved the c_move::handle call lower than getting weapon and weapon_info, but it didn't help

**Comment by pinkway** [comment]
is there really something wrong with your weapon_info getter function, i created a separate weapon interface and already get weapon_info from there and everything works fine

**Comment by pinkway** [comment]
"i think it would be better to rename c_local_player to smth like c_client_move, since this class is not really a local_player, and also move local_player pointer to the valve namespace, since the current layout might confuse people as it happened to you"

in fact, i liked this idea and i will use it, i don't think it can confuse anyone, so i don't see the point in renaming it

**Comment by pinkway** [comment]
![image](https://user-images.githubusercontent.com/131168457/233058292-598f04b6-e152-4e47-bc5f-5805c47db805.png)
i compiled a clean sdk to prove it to you

**Comment by lagcomp** [comment]
> ![image](https://user-images.githubusercontent.com/131168457/233058292-598f04b6-e152-4e47-bc5f-5805c47db805.png) i compiled a clean sdk to prove it to you

thanks, so i noticed that this problem only occurs with the msvc compiler, i'll push a fix in a few minutes
