### ISSUE TITLE
Renderer?

### ISSUE THREAD

**Issue by ZeroXKiritsu** [lagcomp/csgo_sdk#95]
And where is the render? Or in your opinion it is not needed ? What is a base without a render?

**Comment by rollraw** [comment]
Карен пидорас

**Comment by ZeroXKiritsu** [comment]
> Карен пидорас


Нахуй иди просто, моя активность github тебя не касается

**Comment by d4rkd3n1337** [comment]
Карен пидарас

**Comment by ZeroXKiritsu** [comment]
> Карен пидарас

Ещё один нах иди

**Comment by d4rkd3n1337** [comment]
Тебя наконецта из клининга уволили?)

**Comment by ZeroXKiritsu** [comment]
> Тебя наконецта из клининга уволили?)

Откуда ?

**Comment by rollraw** [comment]
армен сосал его ебали ну так в общем то и вылез каренчик и как начнет мяукать, все в поезде аж ахуели от происходящего и начали в окна прыгать, ну вот в общем летят они на парашютах, приземляются где-то в поле а тут карен уже козу ебёт. вы бы видели их лица

**Comment by ZeroXKiritsu** [comment]
> армен сосал его ебали ну так в общем то и вылез каренчик и как начнет на четвереньках ползать и гавкать, все в поезде аж ахуели от происходящего и начали в окна прыгать, ну вот в общем летят они на парашютах, приземляются где-то в поле а там карен уже козу ебёт. вы бы видели их лица...

Ну можешь дальше позориться и идти так же нахуй дальше

**Comment by HyoukivUkraine** [comment]
sboriwe pasters sobralos
slazyyyy gde bit_map 😳 
blyat namingi isportil slazyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy 😢

**Comment by lagcomp** [comment]
> And where is the render? Or in your opinion it is not needed ? What is a base without a render?

the base has an **imgui**, so you can use it **as a renderer**
just **grab the data for rendering** in the game thread n **pass it to the dx9 one**, or **make a swapchain**
